Migrations comments
EV-charges/api pull request #14
Opened 2023-06-14 10:03 UTC by Ruby821

2023-06-15 16:17 UTC, MarkAntipin approved these changes

2023-06-15 16:17 UTC, MarkAntipin commented on src/dal/postgres/places.py
> +    async def place_is_exist(
place_is_exist -> is_place_exist и должна возвращать bool
+ не надо передавать туда place_sources объект, передай просто place_id + source, так понятнее будет

2023-06-15 16:17 UTC, MarkAntipin commented on src/services/comments.py
> +            return "Place doesn't exist"
ошибку надо кинуть кастовую

2023-06-15 16:17 UTC, MarkAntipin commented on src/dal/postgres/comments.py
> +        )
мы же договорились что выпиливаем все лишнее, а проверку на наличие такой точки, мы делаем через другой запрос

+ query - это запрос, а ты приравнял query - уже ответу на запрос.

2023-06-15 16:18 UTC, MarkAntipin requested changes
Поправь, то что обсуждали

2023-06-15 16:52 UTC, Ruby821 commented on src/dal/postgres/places.py
> +    async def place_is_exist(
Нам необходимо заодно получить из этого запроса place_id, который будем использовать при вставке коммента. Поэтому нужно int | None, а не bool.
Или как то по другому нужно реализовать?

2023-06-15 17:00 UTC, Ruby821 commented on src/dal/postgres/places.py
> +    async def place_is_exist(
Подскажи, нужно ли возвращать id только что добавленного коммента, или вернуть только bool?

2023-06-15 18:12 UTC, Ruby821 commented
Правильно ли добавлять второй блок except, как я сделал в routers/comments.py?
Как лучше обработать if response, if not response в services?

2023-06-19 08:26 UTC, MarkAntipin approved these changes

2023-06-19 08:26 UTC, merged